#!/usr/bin/env bash

set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

trigger-swarm-scheduler-stop() {
  declare desc="stops or also removes a stack from the swarm"
  declare trigger="scheduler-stop"
  declare DOKKU_SCHEDULER="$1" APP="$2" REMOVE_CONTAINERS="$3"

  if [[ "$DOKKU_SCHEDULER" != "swarm" ]]; then
    return
  fi

  if [[ "$REMOVE_CONTAINERS" = true ]]; then
    dokku_log_info1 "Removing stack $APP"

    APP="$APP" "$DOCKER_BIN" stack rm "$APP"

  else
    dokku_log_info1 "Removing stack $APP"

    APP="$APP" "$DOCKER_BIN" stack rm "$APP"
  fi
}

trigger-swarm-scheduler-stop "$@"
